### ISSUE TITLE
question about mathematic detail

### ISSUE THREAD

**Issue by Fangwq** [mariogeiger/feature_lazy#16]
I read your paper `Geometric compression of invariant manifolds in neural nets` recently, but I could not understand the deduction in appendix C.1. Would you like to explain it in detail( For example, variable \mu_1 )? Thank you very much!

**Comment by jonas-paccolat** [comment]
Thank you for your interest in our work. Please find below some more details on the computation.

[explicit-appendix-C1.pdf](https://github.com/mariogeiger/feature_lazy/files/8583159/explicit-appendix-C1.pdf)

**Comment by Fangwq** [comment]
Thank you for your clarification!
