### ISSUE TITLE
question about the code in 'kernels.py'

### ISSUE THREAD

**Issue by Fangwq** [mariogeiger/feature_lazy#17]
I read the codes for the paper `Geometric compression of invariant manifolds in neural nets` recently. And I have a question about the following codes in the file `kernels.py`:
```
if sum(p.numel() for p in current) > 2e9 // (8 * (len(xtr) + len(xte))):
     if len(current) > 1:
             params.append(current[:-1])
             current = current[-1:]
      else:
             params.append(current)
             current = []
```
What are these codes for?  Would you like to explain it for me? Thank you very much!

**Comment by mariogeiger** [comment]
Hi, It splits the computation into chunks to avoid memory overflows.

After the for loop, `params` is a list of lists satisfying the following constraint: each list of at least 2 element must contain less than N parameters. Where `N = 2e9 // (8 * (len(xtr) + len(xte)))`

**Comment by Fangwq** [comment]
Thanks for your clarification!
